from pathlib import Path

ROOT_DIR = Path(__file__).parent.parent.parent
DATA_DIR = ROOT_DIR / "data"
RAW_DIR = DATA_DIR / "raw"
PROCESSED_DIR = DATA_DIR / "processed"
QUALITY_REPORTS_DIR = DATA_DIR / "quality_reports"
CORPORA_DIR = DATA_DIR / "corpora"
DB_PATH = CORPORA_DIR / "eba-corpus.db"

# Quality thresholds (PRD 11.1)
QUALITY_SCORE_THRESHOLD = 0.85
PAGE_COVERAGE_THRESHOLD = 0.85
CITATION_ROUNDTRIP_THRESHOLD = 0.95
BROKEN_WORD_RATIO_MAX = 0.05
EMPTY_PAGE_RATIO_MAX = 0.10
DUPLICATE_CHUNK_RATIO_MAX = 0.05
PARAGRAPH_REF_DETECTION_MIN = 0.70
MIN_CHARS_TOTAL = 1000

LANGUAGE = "en"
ALLOWED_DOMAIN = "eba.europa.eu"
DOWNLOAD_RETRIES = 3
